### ISSUE TITLE
第八章 智能编程语言实验mlu-实验5-2-智能编程语言性能优化实验-v5_mul

### ISSUE THREAD

**Issue by kplngyi** [Yuichi1001/2024-AICS-EXP#11]
大佬们好，这个仓库的意义太重大了，很棒。
我遇到了一个问题，在OJ提交的时候爆了超出内存的错误，我怀疑是后边的评测开的内存太大，然后只提交了01_scalar.mlu文件，结果还是出现了内存错误
<img width="822" alt="Screenshot 2024-05-28 at 4 27 19 PM" src="https://github.com/Yuichi1001/2024-AICS-EXP/assets/54162311/39ebc2f1-084c-4ee1-8284-9f1ba039dbcf">
请问有没有什么解决方法？

**Comment by Yuichi1001** [comment]
这个是评测系统的问题噢 课程群里艾特一下老师让他修复

**Comment by Yuichi1001** [comment]
题目答案我都是在希冀评测完没问题才上传到仓库里的 应该不是答案问题

**Comment by Yuichi1001** [comment]
或者可以尝试多提交几次

**Comment by kplngyi** [comment]
收到，谢谢你。
