### ISSUE TITLE
请问如何登陆南京智能计算中心算力平台

### ISSUE THREAD

**Issue by GaoXiangYa** [Yuichi1001/2024-AICS-EXP#12]
没办法注册账号，如何登陆

**Comment by Yuichi1001** [comment]
账号是我们这学期开课的时候老师统一提供的，需要mlu或者gpu资源的话也可以去别的算力平台租 网上搜搜应该有很多算力平台 都不贵

**Comment by GaoXiangYa** [comment]
好的，谢谢，请问直接用寒武纪的实验平台可以吗

**Comment by GaoXiangYa** [comment]
大佬能在github上传一下lab初始的代码吗，打算做一下这个Lab

**Comment by Yuichi1001** [comment]
> 大佬能在github上传一下lab初始的代码吗，打算做一下这个Lab

代码仓库里有网盘链接 有些数据集比较大传不上来 所以我放在百度网盘里

**Comment by Yuichi1001** [comment]
> 好的，谢谢，请问直接用寒武纪的实验平台可以吗

那肯定可以 实验本身要用的就是寒武纪mlu

**Comment by GaoXiangYa** [comment]
大佬，请问你上传的数据集完整吗
```
TRAIN_DATA = "train-images-idx3-ubyte"
TRAIN_LABEL = "train-labels-idx1-ubyte"
TEST_DATA = "t10k-images-idx3-ubyte"
TEST_LABEL = "t10k-labels-idx1-ubyte"
```
我这边从百度网盘下载的数据集只有：
```
TEST_LABEL = "t10k-labels-idx1-ubyte"
TRAIN_LABEL = "train-labels-idx1-ubyte"
```

感谢大佬

**Comment by Yuichi1001** [comment]
> 大佬，请问你上传的数据集完整吗
> ```
> TRAIN_DATA = "train-images-idx3-ubyte"
> TRAIN_LABEL = "train-labels-idx1-ubyte"
> TEST_DATA = "t10k-images-idx3-ubyte"
> TEST_LABEL = "t10k-labels-idx1-ubyte"
> ```
> 我这边从百度网盘下载的数据集只有：
> ```
> TEST_LABEL = "t10k-labels-idx1-ubyte"
> TRAIN_LABEL = "train-labels-idx1-ubyte"
> ```
> 
> 感谢大佬

这是实验几的啊  时间有点久忘记了

**Comment by GaoXiangYa** [comment]
实验2的，手写数字识别的

**Comment by Yuichi1001** [comment]
> 实验2的，手写数字识别的

![image](https://github.com/user-attachments/assets/401c26c7-52fc-4ddb-9a99-98440415d767)
我这里看链接里有啊

**Comment by GaoXiangYa** [comment]
哦哦，好的谢谢大佬，是我传到实验平台上系统没给我传完

**Comment by GaoXiangYa** [comment]
不知道为啥，寒武纪的实验平台上，剩下两个数据集传不上去，明明才50M，没超过1G
![image](https://github.com/user-attachments/assets/0779486a-824e-44fb-9444-b663d622cdb9)

**Comment by Yuichi1001** [comment]
> 不知道为啥，寒武纪的实验平台上，剩下两个数据集传不上去，明明才50M，没超过1G
> ![image](https://github.com/user-attachments/assets/0779486a-824e-44fb-9444-b663d622cdb9)
> 

搞成压缩包 上传以后再解压

**Comment by GaoXiangYa** [comment]
搞成压缩包也不行，压缩完有1Mb大小都无法上传

**Comment by Yuichi1001** [comment]
> 搞成压缩包也不行，压缩完有1Mb大小都无法上传

那这就不清楚了 要不你去其他算力平台租mlu试试

**Comment by Yuichi1001** [comment]
> 搞成压缩包也不行，压缩完有1Mb大小都无法上传

或者问问客服

**Comment by GaoXiangYa** [comment]
好的，谢谢
