### ISSUE TITLE
exp_7_1实验

### ISSUE THREAD

**Issue by Porphy** [Yuichi1001/2024-AICS-EXP#13]
exp_7_1实验貌似cg系统上面通不过，出现下面的错误，请问是哪里出了问题么？
Runtime Error
In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/extension.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/include/customed_ops.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:3: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas] #pragma omp parallel for if ((end - begin) >= grain_size) In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/util/exceptions.h:35:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/core/allocator.h:35, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/core/tensor_impl.h:37, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:34, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/util/cnlog.h: In function ‘std::ostream& torch_mlu::GenerateBasicMessage(std::ostream&, const T&) [with T = c10::ArrayRef; std::ostream = std::basic_ostream]’: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/util/cnlog.h:179:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] for (int64_t i = 0; i < t.size(); ++i) { ~~^~~~~~~~~~ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/specificViewOps.h:32:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/optimViewChain.h:34, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/viewChain.h:34, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/core/tensor_impl.h:43, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:34, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h: In member function ‘virtual bool torch_mlu::BaseViewOp::hasCnnlSpecificFunction()’: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h:128:45: warning: no return statement in function returning non-void [-Wreturn-type] virtual bool hasCnnlSpecificFunction() {} ^ /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h: In member function ‘virtual at::Tensor torch_mlu::BaseViewOp::runCnnlSpecificFunction(const at::Tensor&)’: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h:130:74: warning: no return statement in function returning non-void [-Wreturn-type] virtual at::Tensor runCnnlSpecificFunction(const at::Tensor& input) {} ^ /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h: In member function ‘virtual std::vector torch_mlu::BaseViewOp::inferCnnlSpecificSizes(const std::vector&)’: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h:132:98: warning: no return statement in function returning non-void [-Wreturn-type] virtual std::vector inferCnnlSpecificSizes(const std::vector& input_size) {} ^ /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h: In member function ‘virtual std::string torch_mlu::BaseViewOp::parameterToString() const’: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h:134:52: warning: no return statement in function returning non-void [-Wreturn-type] virtual std::string parameterToString() const {} ^ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:33:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/cnnl/internal/cnnl_internal.h: At global scope: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/cnnl/internal/cnnl_internal.h:51:54: warning: ‘IntList’ is deprecated [-Wdeprecated-declarations] int groups); ^ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/c10/core/MemoryFormat.h:5:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:5, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/Context.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/extension.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/include/customed_ops.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:3: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h:41:7: note: declared here class ArrayRef final { ^~~~~~~~ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:33:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/cnnl/internal/cnnl_internal.h:51:54: warning: ‘IntList’ is deprecated [-Wdeprecated-declarations] int groups); ^ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/c10/core/MemoryFormat.h:5:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:5, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/Context.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/torch/extension.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/include/customed_ops.h:4, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:3: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h:41:7: note: declared here class ArrayRef final { ^~~~~~~~ /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp: In function ‘at::Tensor active_sigmoid_mlu(at::Tensor)’: /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:11:34: error: ‘cnnl_contiguous’ is not a member of ‘torch_mlu’ auto x_contiguous = torch_mlu::cnnl_contiguous(x); ^~~~~~~~~~~~~~~ /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:11:34: note: suggested alternative: In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42:0, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:45:12: note: ‘torch_mlu::cnnl::ops::cnnl_contiguous’ at::Tensor cnnl_contiguous(const at::Tensor& input, ^~~~~~~~~~~~~~~ /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:16:34: error: ‘cnnl_contiguous’ is not a member of ‘torch_mlu’ auto y_contiguous = torch_mlu::cnnl_contiguous(y); ^~~~~~~~~~~~~~~ /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:16:34: note: suggested alternative: In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42:0, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:45:12: note: ‘torch_mlu::cnnl::ops::cnnl_contiguous’ at::Tensor cnnl_contiguous(const at::Tensor& input, ^~~~~~~~~~~~~~~ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/cnnl/internal/cnnl_internal.h:6:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:33, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/ReduceOpsUtils.h: At global scope: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/ReduceOpsUtils.h:248:23: warning: ‘at::TensorIterator at::native::make_reduction(const char*, at::Tensor&, at::Tensor&, const at::Tensor&, c10::IntArrayRef, bool, c10::ScalarType)’ defined but not used [-Wunused-function] static TensorIterator make_reduction( ^~~~~~~~~~~~~~ /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/ReduceOpsUtils.h:199:23: warning: ‘at::TensorIterator at::native::make_reduction(const char*, at::Tensor&, const at::Tensor&, c10::IntArrayRef, bool, c10::ScalarType)’ defined but not used [-Wunused-function] static TensorIterator make_reduction( ^~~~~~~~~~~~~~ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/cnnl/internal/cnnl_internal.h:4:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/cnnl_util.h:33, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:42, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/IndexingUtils.h:72:1: warning: ‘std::tuple > > at::native::transposeToFront(at::Tensor, at::TensorList)’ defined but not used [-Wunused-function] transposeToFront(Tensor self, TensorList indices) { ^~~~~~~~~~~~~~~~ /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/IndexingUtils.h:54:13: warning: ‘bool at::native::hasContiguousSubspace(at::TensorList)’ defined but not used [-Wunused-function] static bool hasContiguousSubspace(TensorList tl) { ^~~~~~~~~~~~~~~~~~~~~ /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/IndexingUtils.h:43:13: warning: ‘void at::native::checkIndexTensorTypes(at::TensorList)’ defined but not used [-Wunused-function] static void checkIndexTensorTypes(TensorList indices) { ^~~~~~~~~~~~~~~~~~~~~ /torch/venv3/pytorch/lib/python3.7/site-packages/torch/include/ATen/native/IndexingUtils.h:13:28: warning: ‘std::vector at::native::expandTensors(const at::Tensor&, at::TensorList)’ defined but not used [-Wunused-function] static std::vector expandTensors(const Tensor & self, TensorList indices) { ^~~~~~~~~~~~~ In file included from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/specificViewOps.h:32:0, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/optimViewChain.h:34, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/viewChain.h:34, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/core/tensor_impl.h:43, from /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/operators/bang/bang_kernel.h:34, from /cg/code_chap_5_student/ori_5_1_custom_pytorch_mlu_op/mlu_custom_ext/mlu/src/bang_sigmoid.cpp:6: /torch/venv3/pytorch/lib/python3.7/site-packages/torch_mlu/csrc/aten/cnnl/baseViewOps.h:91:20: warning: ‘std::string torch_mlu::viewTypeToString(const torch_mlu::ViewsType&)’ defined but not used [-Wunused-function] static std::string viewTypeToString(const ViewsType& type) { ^~~~~~~~~~~~~~~~ /opt/py3.7/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'extra_cflags', 'verbose' warnings.warn(msg) /torch/venv3/pytorch/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. setuptools.SetuptoolsDeprecationWarning, /torch/venv3/pytorch/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools. EasyInstallDeprecationWarning, /torch/venv3/pytorch/lib/python3.7/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 1.14.0-torch1.6 is an invalid version and will not be supported in a future release PkgResourcesDeprecationWarning, error: command 'gcc' failed with exit status 1

**Comment by Yuichi1001** [comment]
抱歉 我现在已经没有评测系统的权限 不过只要题目没改的话代码应该是没有问题的 之前很多朋友都已经在评测平台测试过

根据你的报错 貌似有gcc编译问题 torch_mlu库报错问题等 感觉可能是环境出了问题 你可以检查一下

**Comment by Porphy** [comment]
谢谢，已解决！

**Comment by closetothesuu** [comment]
> 谢谢，已解决！

怎么解决的呀，能不能教教我，谢谢啦

**Comment by Porphy** [comment]
> > 谢谢，已解决！
> 
> 怎么解决的呀，能不能教教我，谢谢啦

我们实验平台上给的题目代码和实验指导书上的代码在头文件上有一些出入。核心代码不用变，按实验平台上给的题目代码引入正确的头文件就行。

**Comment by closetothesuu** [comment]
> > > 谢谢，已解决！
> > 
> > 
> > 怎么解决的呀，能不能教教我，谢谢啦
> 
> 我们实验平台上给的题目代码和实验指导书上的代码在头文件上有一些出入。核心代码不用变，按实验平台上给的题目代码引入正确的头文件就行。

感谢感谢，已解决

**Comment by nuonuoxiangyaofeigaogao** [comment]
@Porphy @closetothesuu 大佬们！可以看一下你们提交的文件目录嘛，我的目录是这样的，代码都没有改变呜呜呜

![Image](https://github.com/user-attachments/assets/75c677f3-087c-46da-a8e5-abfcb2b9b3e8)
