### ISSUE TITLE
exp4_4文件名解决方法

### ISSUE THREAD

**Issue by yangyu-wang** [Yuichi1001/2024-AICS-EXP#2]
链接库生成的时候没有参数可以直接去掉后缀，所以只能更加简单粗暴一点，直接修改生成后的.so文件的名字即可，另外，由于我是在test_hsigmoid.py和evaluate_cpu.py中直接import hsigmoid_extension，所以还需要将.so文件移动到上一级文件夹中，也就是需要与两个py文件处于相同的路径下（虽然交的时候所有文件都在一起，但是实际测试时仍然按照原先的文件夹排布）。代码如下：
```
from setuptools import setup
from torch.utils import cpp_extension
import os

setup(
    name='hsigmoid_c', # 给出编译后的链接库名称
    ext_modules=[cpp_extension.CppExtension('hsigmoid_c', ['hsigmoid.cpp'])],  # 以正确的格式给出编译文件即编译函数
    cmdclass={'build_ext': cpp_extension.BuildExtension}, # 执行编译命令设置
)

# 重命名so文件并将该文件移动到上一级文件夹中
directory = './'
# 获取当前脚本所在的文件夹路径
current_dir = os.path.dirname(os.path.abspath(__file__))
# 遍历目录中的所有文件
for filename in os.listdir(directory):
    if filename.endswith(".so"):
        new_filename = "hsigmoid_c.so"
        os.rename(os.path.join(directory, filename), os.path.join(os.path.dirname(current_dir), new_filename))
        
print("generate .so PASS!\n")
```

**Comment by Yuichi1001** [comment]
确实可以通过重命名的方法来解决这个问题，感谢！ 您可以提交pr，我把您的代码合并到主分支。提交pr的时候移动.so文件那一部分可以去掉，毕竟最后交到测评系统里的时候都是在同一个目录下。 如果您没空的话我过两天修改下代码自己再提交一下

**Comment by yangyu-wang** [comment]
> 确实可以通过重命名的方法来解决这个问题，感谢！ 您可以提交pr，我把您的代码合并到主分支。提交pr的时候移动.so文件那一部分可以去掉，毕竟最后交到测评系统里的时候都是在同一个目录下。如果您没空的话我过两天修改下代码自己再提交一下

感谢认可。在我实际测试中，没有移动.so文件这一步是不行的，依然会显示no moudle，我不知道是否和您的程序有其他差别，所以如果您有时间可以尝试一下

**Comment by Yuichi1001** [comment]
好的，感谢！明天更新第五章的时候我顺便测试一下

**Comment by Yuichi1001** [comment]
经过测试确实在提交的时候还是得把生成的.so移到上一级目录，猜测可能是评测系统在解压文件的时候把setup.py和hsigmoid.cpp解压到内层目录里了。 目前仓库代码已修改，感谢您的贡献！

**Comment by Jayden-qing** [comment]
如果不修改这段代码是不是会出现以下报错：
 File "test_hsigmoid.py", line 6, in <module>
    import hsigmoid_extension 
ModuleNotFoundError: No module named 'hsigmoid_extension'

**Comment by Jayden-qing** [comment]
遇见这个问题的同学记得把以上代码的hsigmoid_c.so文件名改为hsigmoid_extension.so
