### ISSUE TITLE
exp_5_3在评测平台上的运行时间

### ISSUE THREAD

**Issue by ly63231** [Yuichi1001/2024-AICS-EXP#3]
大概运行了多久呀，我这边评测了4个小时还没结束

**Comment by Yuichi1001** [comment]
您好 我提交的时候在系统里评测了一个多小时就过了 可能是系统那边压力大了跑的比较慢

**Comment by ly63231** [comment]
好的，应该确实是系统的问题，大概5个小时左右评测通过了，谢谢你~
