### ISSUE TITLE
第六章实验

### ISSUE THREAD

**Issue by DragonnZhang** [Yuichi1001/2024-AICS-EXP#5]
大佬你好，请问第六章实验还会更新吗？

**Comment by Yuichi1001** [comment]
最近沉迷lol😢 过两天就做

**Comment by Yuichi1001** [comment]
已更新

**Comment by DragonnZhang** [comment]
太牛了

**Comment by Yuichi1001** [comment]
代码现在还有问题 明天改改

**Comment by Yuichi1001** [comment]
> 太牛了

又更新了一次 应该没啥问题了 peresult对得上result了

**Comment by slnrm** [comment]
你好，最后的pe_result只能和result对上一组结果吗

**Comment by Yuichi1001** [comment]
> 吗

可以对上所有结果。在wave中观测pe_result变量和pe_vld_o变量 用滚轮缩小进度条 可以看到pe_vld_o有四个波峰 每个波峰所在的坐标对应的pe_result都和result中的值一一对应

**Comment by Yuichi1001** [comment]
> 你好，最后的pe_result只能和result对上一组结果吗

可以对上所有结果。在wave中观测pe_result变量和pe_vld_o变量 用滚轮缩小进度条 可以看到pe_vld_o有四个波峰 每个波峰所在的坐标对应的pe_result都和result中的值一一对应

**Comment by slnrm** [comment]
看到拉  谢谢谢谢

**Comment by Yuichi1001** [comment]
> 看到拉  谢谢谢谢  

点点star谢谢喵🤩

**Comment by slnrm** [comment]
我要点十个
