### ISSUE TITLE
关于理论部分教学

### ISSUE THREAD

**Issue by Tristan0318** [Yuichi1001/2024-AICS-EXP#6]
Hi，同学你好。我是来自SHU大的同学，也担任了这门课程的助教。但是目前我们学校还使用的是第一版教材和v2实验内容，可能明年要更新一下内容。想问问果壳有没有使用《智能计算系统-从深度学习到大模型 第2版》新版本的书，同时老师有没有给相关的课件，如果有课件的话能不能也上传一下呢，谢谢！:-)

**Comment by Yuichi1001** [comment]
您好 书的话我这里没有 课件有部分更新了新版 我现在上传

**Comment by Yuichi1001** [comment]
已更新

**Comment by Tristan0318** [comment]
谢谢！这样我也可以更新一下我们学校的实验教学环节了:-)
